### ISSUE TITLE
Build Error while building source code 

### ISSUE THREAD

**Issue by GowriAradhya** [BiancoRoyal/node-red-contrib-modbus#176]
**I'm submitting a ...**  (check one with "x")

## Support/Advice
 - support/advice request => **Please do not submit support requests here**, instead use [the link to our support page](https://bianco-royal.com/supporter.html), please!

## Feature
 - ( ) feature request
 
 **What is the motivation / use case for changing the behavior?**
 

## Simple question to get some hint
 - ( ) simple question => please visit the Wiki, the YouTube tutorials and the Info tab by clicking on the node inside Node-RED before
 - (x ) help wanted => you read all information and watched relevant YouTube tutorials, but you need more help

## Problem
 - ( x) bug report => please search github for a similar issue or PR and test Modbus problems with the [modbus-serial](https://github.com/yaacov/node-modbus-serial) package before submitting
 - ( ) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
Unable to build source code for release 5.2.0
 
 **Expected behavior**
 
 Build must be successful 

 **Minimal reproduction of the problem with instructions**
   1. clone the repository from github (version 5.2.0)
   2. npm install --only=dev
   3. npm install --save-dev gulp
   4. gulp publish
   5. npm install --production
   
### Your Environment
**Please tell us about your environment:**
node:12.14.1-buster-slim 

  * Device :
    
    - ( ) macOS: v 
    - (x ) Linux: v debian 9
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
* **node-red-contrib-modbus version:** v5.2.0

* **Node:** (min. 10.x)
   `node --version` = v12.14.1

* **Error message**
[12:09:08] /home/nodered/node-red/proxy-node-red-contrib-modbus/node_modules/requizzle/lib/requizzle.js:45
	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
	               ^

TypeError: Cannot read property '0' of null
    at isNativeModule (/home/nodered/node-red/proxy-node-red-contrib-modbus/node_modules/requizzle/lib/requizzle.js:45:17)
    at Requizzle.requizzle (/home/nodered/node-red/proxy-node-red-contrib-modbus/node_modules/requizzle/lib/requizzle.js:82:6)
    at infectProxy (/home/nodered/node-red/proxy-node-red-contrib-modbus/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/home/nodered/node-red/proxy-node-red-contrib-modbus/node_modules/requizzle/lib/loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nodered/node-red/proxy-node-red-contrib-modbus/node_modules/jsdoc/lib/jsdoc/fs.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Object.load (/home/nodered/node-red/proxy-node-red-contrib-modbus/node_modules/requizzle/lib/loader.js:112:15)

[12:09:08] JSDoc returned with error code: 1
[12:09:08] 'doc' errored after 112 ms
[12:09:08] Error: JSDoc closed with error code: 1
    at ChildProcess.<anonymous> (/home/nodered/node-red/proxy-node-red-contrib-modbus/node_modules/gulp-jsdoc3/dist/gulp-jsdoc.js:146:32)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:498:23)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[12:09:08] 'publish' errored after 3.55 s

**Comment by biancode** [comment]
see #144 it is not compatible with Nodejs v12 for now and has compile errors
